output "cluster_id" {
  description = "The name/id of the EKS cluster"
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}
output "worker_security_group_id" {
  description = "Security group ids attached to the workers."
  value       = module.eks.worker_security_group_id
}

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.eks.config_map_aws_auth
# }

//output "node_group_name" {
//  description = "Outputs from node groups"
//  value       = module.eks.node_groups.node_group_1.node_group_name
//}

output "eks_cluster_iam_role_arn" {
  description = "iam role arn or eks cluster"
  value       = module.eks.cluster_iam_role_arn
}

output "worker_iam_role_arn" {
  value = module.eks.worker_iam_role_arn
}

output "worker_iam_role_name" {
  value = module.eks.worker_iam_role_name
}

output "oidc_provider_arn" {
  value = module.eks.oidc_provider_arn
}

output "cluster_oidc_issuer_url" {
  value = module.eks.cluster_oidc_issuer_url
}

output "cluster_iam_role_name" {
  value = module.eks.cluster_iam_role_name
}
