name: Prod Deploy

on:
  push:
    branches:
      - add-eks
    # paths:
    #   - "deployment/**"

defaults:
  run:
    working-directory: deployment/production

jobs:
  Plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      tf_version: 1.0.6
      tg_version: v0.31.11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.31.8

      - name: Interact with Terragrunt
        run: |
          ls
          terragrunt --version
          terraform --version

      - name: Terragrunt plan-all
        run: |
          terragrunt plan-all -out=plan

      # - name: Terragrunt apply-all
      #   run: |
      #     terragrunt run-all apply --terragrunt-non-interactive
