name: Prod Deploy

on:
  push:
    branches:
      - add-eks
    # paths:
    #   - "deployment/**"

defaults:
  run:
    working-directory: production

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
    - uses: actions/checkout@v1
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.31.8
    - name: Interact with Terragrunt
      run: |
        ls
        terragrunt --version

    # - name: Setup infra modules deploy key
    #   run: |
    #     mkdir ~/.ssh
    #     echo "${{ secrets.INFRA_MODULES_DEPLOY_KEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan -t rsa github.com

    - name: Terragrunt plan-all
      run: |
        terragrunt run-all plan

    # - name: Terragrunt apply-all
    #   run: |
    #     terragrunt run-all apply --terragrunt-non-interactive
